### Get all Pokemons
GET http://localhost:3003/pokemon/allpokemons
Content-Type: application/json

{
    "page":1
}
### Get Pokemon by Name
GET http://localhost:3003/pokemon/charmander

### Get Pokemon by Type
GET http://localhost:3003/pokemon/type/ice

### Get Pokemon by Types
GET http://localhost:3003/pokemon/types/pokemons
Content-Type: application/json

{
    "type1": "poison",
    "type2": "grass"  
}

### Get amount Pokemons
GET http://localhost:3003/pokemon/count/pokemons



