CREATE TABLE IF NOT EXISTS Pokemons(
  Id INT NOT NULL,
  Name VARCHAR(255) NOT NULL,
  Pokedex_number INT,
  Img_name INT,
  Generation INT,
  Evolution_stage INT,
  Evolved INT,
  Family_id INT,
  Cross_gen INT,
  Type_1 VARCHAR(255),
  Type_2 VARCHAR(255),
  Weather_1 VARCHAR(255),
  Weather_2 VARCHAR(255),
  Stat_Total INT,
  Atk INT,
  Def INT,
  Sta INT,
  Legendary INT,
  Aquireable INT,
  Spawns INT,
  Regional INT,
  Raidable INT,
  Hatchable INT,
  Shiny INT,
  Nest INT,
  New INT,
  Not_Gettable INT,
  Future_Evolve INT,
  100_cp_40 INT,
  100_cp_39 INT
);