export interface InputDTO  {
  type1?: string,
  type2?: string,  
}

export type pokemon = {
    Id: number,
    Name: string,
    Pokedex_number: number,
    Img_name: number,
    Generation: number,
    Evolution_stage: number,
    Evolved: number,
    Family_id: number,
    Cross_gen: number,
    Type_1: string,
    Type_2: string,
    Weather_1: string,
    Weather_2: string,
    Stat_total: number,
    Atk: number,
    Def: number,
    Sta: number,
    Legendary: number,
    Aquireable: number,
    Spawns: number,
    Regional: number,
    Raidable: number,
    Hatchable: number,
    Shiny: number,
    Nest: number,
    New: number,
    Not_gettable: number,
    Future_evolve: number,
    cp_40: number,
    cp_39: number
}
